import '../styles/globals.css'
import { AuthProvider } from '../context/AuthContext';

import SidebarNav from '../components/SidebarNav';
import { useRouter } from "next/router";
import Head from 'next/head';
export default function App({ Component, pageProps }) {
  const router = useRouter();
  const isLoginPage = router.pathname === '/Login' ;
  const passwrdReset = router.pathname === '/passowrd-forgot';
   // Set isLoginPage to true if current route is '/login'
  // Extract the segments of the URL from router.asPath
  const pathSegments = router.asPath.split('/');

  // Check if 'treatmentplan' segment is followed by another segment
  const isExcludedPage =
  (pathSegments.includes('refinementplan') || pathSegments.includes('treatmentplan') ) &&
  pathSegments.length > 2;
  return (
    
    <AuthProvider>
   
    
    {isLoginPage || passwrdReset ? (
          // Render without SidebarNav for login page
          <>
            <Head>
              <title>Delivery Portal</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.png" />
            </Head>
            <Component {...pageProps} />
          </>
        ): isExcludedPage ? (
          <>
            <Head>
              <title>Delivery Platform</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.png" />
            </Head>
            <Component {...pageProps} />
          </>
        ) : (
          // Render with SidebarNav for other pages
          
          <SidebarNav>
            <Head>
            <title>Delivery Portal</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.png" />
            </Head>
            <Component {...pageProps} />
          </SidebarNav>
        )}
    
   
   
    
    </AuthProvider>
  );
}
